### PR TITLE
Fix broken schema discovery docs link

### PR DESCRIPTION
**Pull request by alexras**
# Description of change

In the repository's README, the link to the best practices documentation for schema discovery is broken. This PR updates the link to reflect the analogous page in singer-io/getting-started

# Manual QA steps
 - Click the link. It shouldn't 404.
 
# Risks
 - None.
 
# Rollback steps
 - revert this branch

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @alexras, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @alexras!

Thank you for signing the Singer Contribution License Agreement.

**Comment by alexras** [comment]
Just wanted to check in on this.

**Comment by alexras** [comment]
Wanted to check in again here. Is there still interest in landing this change?

**Comment by alexras** [comment]
Closing this due to inactivity. Feel free to reopen if you'd like.

**Pull request closed without merging**
